### ISSUE TITLE
Unnecessary color mix nodes [cycles]

### ISSUE THREAD

**Issue by LukeV1** [johnzero7/XNALaraMesh#10]
When converting materials to cycles, a color mix node without any functionality gets added inbetween each texture and the next node, which unnecessarily enlarges the node tree and also may slightly increase rendertime (if many materials get converted)...
![xnalara_1](https://user-images.githubusercontent.com/8466561/28830338-b44dfb76-76d6-11e7-9943-4e0a0a8e18f3.png)
[meaning the selected ones]

This may not be an issue but an intended functionality, but i see no other way than opening an issue to become clear about that.

Thanks for that great addon!

**Comment by Gnates** [comment]
I've noticed this too.

**Comment by johnzero7** [comment]
Those nodes are there for mixing multiple textures.
There reason for the mixnode to be present even when there is only one texture is mainly my laziness :P
Maybe I will correct this at some point, but as it doesn't cause many problems I will leave it for now.
