### ISSUE TITLE
cycles node wiring issue

### ISSUE THREAD

**Issue by LukeV1** [johnzero7/XNALaraMesh#11]
For some specific material (emmissive reflection upon standard material), the cycles converter creates some wrong links between the shaders:
![iss2_1](https://user-images.githubusercontent.com/8466561/29004456-9af4de16-7ac7-11e7-98a9-b1f9731b442e.png)
(complete node setup: http://pasteall.org/pic/show.php?id=117798)
The normalmap gets completely ignored. If rewired to the following layout, the material looks good (and works :)
![iss2_2](https://user-images.githubusercontent.com/8466561/29004458-a4b57c76-7ac7-11e7-91ee-1c98298c5e16.png)
(complete node setup: http://pasteall.org/pic/show.php?id=117799)

Keep up the good work!

**Comment by johnzero7** [comment]
Thanks for reporting this issue. Will fix soon.

**Comment by johnzero7** [comment]
Finally! fixed this bug.
Download v1.8.3

**Comment by LukeV1** [comment]
Thanks a lot for fixing this! Can't wait to import and convert new stuff ;)
