### ISSUE TITLE
Errors popping up when trying to activate the add-on.

### ISSUE THREAD

**Issue by CraftyStarbolt** [johnzero7/XNALaraMesh#12]
![screen shot 2017-09-12 at 01 07 23](https://user-images.githubusercontent.com/31869947/30302180-497fdd90-9757-11e7-8aef-ea9f2713f19b.png)

I'm getting these error messages when I try to tick the add-on in the blender preferences menu. This is Blender 2.7.2 for mac. Any clues for a fix?

**Comment by johnzero7** [comment]
The addon uses features that are only present in Blender 2.74 and up. You need to upgrade Blender.
