### ISSUE TITLE
Blender Friendly Bone Names

### ISSUE THREAD

**Issue by Gnates** [johnzero7/XNALaraMesh#13]
Most of the bipedal XPS models that I've used in Blender have the following bone naming format:
leg **left** toes
leg **left** ankle
leg **left** knee
leg **left** thigh
leg **left** thigh twist
arm **left** shoulder 1
arm **left** shoulder 2
arm **left** shoulder twist
arm **left** elbow
arm **left** wrist
arm **left** finger 1a
arm **left** finger 1b
arm **left** finger 1c

Blender has support for mirroring bone values, if the bone names are same and using the following suffixes:
bone.L  bone.R
bone_L  bone_R
bone_Left bone_Right

Ex:
- legToes.L   legToes.R
- armFinger1a_L   armFinger1a_R
- armWrist_Left   armWrist_Right

Not only does this make bone editing easier, but it also makes mirroring pose values easier.

Can you add an option that will rename all the Left/Right bones to use the suggested suffixes above?

**Comment by Gnates** [comment]
Sorry I just found out the option to rename the bones is already available in the XPS tools panel.

**Comment by johnzero7** [comment]
No problem.  I should have documented the features but hadn't found the time/motivation to do it so far.
