### ISSUE TITLE
What Is The Version Comparison Trying To Do?

### ISSUE THREAD

**Issue by ldo** [johnzero7/XNALaraMesh#16]
I am trying to understand the point of an expression like
> version_mayor <= 1 and version_minor <= 12

Which of these `(`*major*`, `*minor*`)` is supposed to be “old” and which is “new”?
> (0, 13)
> (1, 12)
> (1, 13)

Perhaps the check should be
> (version_mayor, version_minor) <= (1, 12)

**Comment by johnzero7** [comment]
I thought so too. But after some test, this was what worked.
So I guess XPS must have some similar code.
