### ISSUE TITLE
Option: Import XPS model in T-Pose?

### ISSUE THREAD

**Issue by Gnates** [johnzero7/XNALaraMesh#17]
I don't know if this suggestion is possible. Maybe this is something only the XPS model creator can do?
Some XPS models are imported with an A-pose by default.
Setting up an IK rig can be a little difficult for a character with an A-pose.
It would be convenient if both feet are flat on the ground, which should make bone rotation/pole targets a bit more predictable.

Model with A-pose (You tested this 1 before): https://xcrofty.deviantart.com/art/The-King-of-Fighters-XIV-Mai-678059999

Model with T-pose (Almost T-pose/Feet flat on ground): https://lezisell.deviantart.com/art/Batman-Arkham-Knight-Catwoman-90s-XPS-ONLY-719615216

If you need more information, let me know.

**Comment by johnzero7** [comment]
The addon imports the model "as is". So the model can be in T-pose, A-pose or even one arm pointing up and the other down. If that's how the creator made the model, that's what the addon will import.


But after importing you have total freedom to create a new rest pose and after that you can export the model in the new rest pose.

**Comment by Gnates** [comment]
Thanks for the clarification. You can close this.
