### ISSUE TITLE
Connect Bones broken?

### ISSUE THREAD

**Issue by Gnates** [johnzero7/XNALaraMesh#18]
The option to 'Connect Bones' in the XPS import menu doesn't appear to do anything. 
I think I started using XPS Tools last year and I don't remember seeing bones connect to each other after toggling that option.

Haven't seen any errors popup in the console.

Blender 2.78C and 2.79.

**Comment by johnzero7** [comment]
Check, It is working.

You won't be able to see any difference in the armature at first glance.
But if you select the armature, enter pose mode and move some bones around, they will behave differently.

The difference will be more easy to see on the finger bones or the spine. When the bones are not connected you can grab the bones and move them around, the direction of the grabbed bone and its children won't change. 
But if a bones is connected, you will not be able to grab it bone and change the position of the origin. It will only rotate around the tail of its parent.

You can connect bones manually, but be carefull. If the head of the bone you want to connect is not in the same position than the tail of its parent, Blender will change the position of the head of the connected bone to the tail of its parent.

**Comment by Gnates** [comment]
In the picture below, the thigh bones, calf bones, and few other bones are disconnected.
https://i.imgur.com/xYcvJ7p.png
The Connect Bones option does indeed affect the spine and finger bones, but it doesn't affect other bones?
Reason why I ask is because in order for an IK rig for the legs to work, the leg bones need to be connected. It's not a huge deal, but if XPS Tools can pull it off, that would be nice.
I usually just select the tail bone of the parent first, then select the head of the child, then Snap to Active Selection, and then connect them together.

I probably should've asked this a long time ago, do you have a guide to IK Rigging XPS character models?

I can probably show you a little gif of how I currently do it, and you can give some recommendations for me to improve workflow.

**Comment by Gnates** [comment]
Here is my current workflow (also a tutorial I'm working on):
Step 1: https://gfycat.com/UnequaledGracefulBull
Step 2: https://gfycat.com/WhirlwindSmallHyena
Step 3: https://gfycat.com/MeagerOldfashionedGalapagoshawk
Step 4: https://gfycat.com/PleasantGoodnaturedBernesemountaindog

**Comment by johnzero7** [comment]
I see the issue now.
The reason the leg bones are not connected is because they have twist correction bones. 
When a bone as 2 or more children with different origins, the addon does not know witch child bone should be connected so it can't adjust the tail of the bone to make the connection.

I will try to make the addon ignore this twist bones when making the connections.

I don't have any tutorial about IK ringing, but what you are doing is pretty much what I do.

**Comment by johnzero7** [comment]
Good news! New version 1.8.0 is out.
When connection bones it ignores bones with the 'twist' or 'adj' in the name.
Added a button in the bottom of the XPS Bones panel to set a new rest pose.
All you need to do is:
1)select all the meshes you want the new rest pose
2)set the armature as the active object
3)click the button "New Rest Pose"
4)In the view port nothing will change, but now you have a new rest pose.

Enjoy

PS: Nice tutorial.

**Comment by Gnates** [comment]
I came across a problem in v1.8.0 - https://github.com/johnzero7/XNALaraMesh/issues/22
