### ISSUE TITLE
we need multiple ascii file import & same file name import & please add an option for scaling the object before the import action

### ISSUE THREAD

**Issue by enterenter** [johnzero7/XNALaraMesh#19]
we need multiple ascii file import and we need to be the mesh inside blender have the same file name, for example if i import ASCII file with name ( car_hood.ascii ) i will get inside blender the name ( submesh_0.007 ) so we need the mesh inside blender to be the same file name please.
EDIT: and can you please add an option for scaling the object with import, because some objects have a very small scale and when i try to import them to blender with that small scale the mesh messed up.

**Comment by johnzero7** [comment]
Blender doesn't not have a way to select multiple files for import.

Renaming the meshes is not a good idea. Many models are composed by different parts with different names (Head, body, boots, etc.), can't use the name of the file for all these parts. Also, not conserving the original name of each mesh would make it difficult to reexport the model to XPS.

Its better to scale a model after the import.
Scale should not cause any kind of distortion on a model. And in any case scaling before or after would have the same effect.
If the addon has problems with a particular model could you upload the model and indicate the problem so I can reproduce it.

**Comment by enterenter** [comment]
My problem that when i'm trying to import the mesh ( the mesh is: car from NFS Payback )  the mesh gets messy and bubbly like the following photo, i can fix the mesh on max but this gonna takes ages, so do you have any solution for that.
https://i.imgur.com/gh7tfMV.jpg
and do you have this plugin for 3dsmax because i'm a max user and i don't use blender.

**Comment by johnzero7** [comment]
from the image the geometry looks ok, the problem may be the normals. But that seems to be how the models was made.

I don't use 3dsmax so I never tried it, but the only addon for 3DSmax I know can be found here:
https://mariokart64n.deviantart.com
