### ISSUE TITLE
'Import Poses' after 'Rename Bones: XPS to Blender'

### ISSUE THREAD

**Issue by Gnates** [johnzero7/XNALaraMesh#20]
Currently, XPS Tools will not import poses for the bones that have been renamed via the 'XPS to Blender' option.

If you can add support for the renamed bones, that would be great.
Examples:
'arm left shoulder 1' --> 'arm *side* shoulder 1.L'
'arm left shoulder 2' --> 'arm *side* shoulder 2.L'
'arm left elbow' --> 'arm *side* elbow.L'
'arm left wrist' --> 'arm *side* wrist.L
'leg left thigh' --> 'leg *side* thigh.L'
'leg left knee' --> 'leg *side* knee.L'
'leg left ankle' --> 'leg *side* ankle.L'
'leg left toes' --> 'leg *side* toes.L'
etc...

**Comment by johnzero7** [comment]
New version 1.8.0 solves this issue.

**Comment by chocmake** [comment]
Are there some steps to follow to allow importing of pose files in 2.8? As currently the option to import is greyed out in my install and neither the repo, microsite or readme offer any insight into the process.
