### ISSUE TITLE
xnal cant find the xps file when i check the folder..

### ISSUE THREAD

**Issue by scooby117** [johnzero7/XNALaraMesh#21]
when i try to import the model (like i would with MMD or FBX) it wont show the X2M file like it would with mmd and fbx....

**Comment by johnzero7** [comment]
the addon only imports XNALara / XPS models
the only valid extensions are: *.xps *.mesh *.ascii (this are displayed on the top in the import window).

if for some reason you want to disable this filter and see all files in the folder you can click on the funnel icon.
