### ISSUE TITLE
Connect Bones broken? v1.8.0

### ISSUE THREAD

**Issue by Gnates** [johnzero7/XNALaraMesh#22]
Sorry for reopening this issue. (I don't know if this is the correct way to reopen)
Do you mind taking a look at these 2 XPS models?
https://grummel83.deviantart.com/art/Jack-Combi-Suit-XPS-696968363
https://xxkammyxx.deviantart.com/art/Isabella-Valentine-Default-Soul-Calibur-IV-476050511

'Connect Bones' option in v1.8.0 appears to be working correctly with some of the previous models I've tested.
However, I just came across that Jack and Isabella XPS models, and it appears to ignore the 'Connect Bones'/'Connect All' options. It might be some sort of mistake the authors made with the armature, but I'm not sure. 
If it helps you in anyway, I will try looking for other XPS models that might misbehave the same way.

Blender 2.79

Also, thank you for recent update. It makes the workflow much faster. Greatly appreciated.

**Comment by Gnates** [comment]
Little more details:
Mai Shiranui - before v1.8.0 - http://i.imgur.com/xYcvJ7p.png
Mai Shiranui - v1.8.0 - https://i.imgur.com/j6KAgsU.png
- For Mai, in v1.8.0, the connected and disconnected bones look the same, visually.
- Not sure if the disconnected bones are supposed to behave that way.
- Connected bones appear to behave correctly.

Jack - v1.8.0 - https://i.imgur.com/34RVqOH.png
- For Jack, in v1.8.0, the Connect Bones option doesn't have any noticeable affect on the arms and legs.

**Comment by johnzero7** [comment]
Uploaded v1.8.1
It will not connect bones that contain the words 'twist', 'ctr', 'root', 'adj'.
This should be enough for Mai and Jack. But in cases like the left shoulder of Ivy there is nothing the addon can do. Other names, for example "armor left b", will not connect correctly.

The "Connect All" and "Disconnect All" button do not modify the bones, only connect and disconnect all the bones in the armature. I added this feature to use it with props. In many cases of needed to disconnect the bones and doing it manually bone by bone was too much work.

**Comment by Gnates** [comment]
Just tried v1.8.1, it works great. Thank you again!
