### ISSUE TITLE
error when importing to blender 2.8 beta using xps tool v1.9.0 

### ISSUE THREAD

**Issue by NexDeLly** [johnzero7/XNALaraMesh#35]
![1](https://user-images.githubusercontent.com/46098061/50390775-6b9a3080-0761-11e9-8c33-4234bb278e91.png)

i just wanted to notify, after the recent blender 2.8 beta release, none of the xps models are importing correctly, which gave me this error.

**Comment by Gnates** [comment]
Yea, I just took a look at the closed issues, and it appears to have been reported already:
- https://github.com/johnzero7/XNALaraMesh/issues/34

It looks like the Blender Developers are still introducing new changes to the Python API.
I need to check if the original 2.80 beta release is available for download.

In related news, the Blender 2.8 branch has been merged into Master:
- https://devtalk.blender.org/t/31-december-2018-upcoming/4506

**Comment by johnzero7** [comment]
Fixed in master branch and release 1.9.1
