### ISSUE TITLE
Blender 2.80 Feature - Import XPS model into New Collection

### ISSUE THREAD

**Issue by Gnates** [johnzero7/XNALaraMesh#36]
Hey, happy holidays.
Unfortunately, I don't have an older 2.80 beta nightly build, so I will have to wait till the Blender devs finalize the API again.

In the meantime, I do have another feature request: 
- Import Option: Import XPS model into New Collection
-- If possible, automatically rename Collection to identify XPS model

**Comment by Gnates** [comment]
Yea, I had a feeling the renaming option would be severely limited, so the "XPS Model.001" is probably the best solution. Thanks!

Regarding the recent problem with the API changes, will we be able to use the nightly 2.80 beta builds again with the next version of XPS Tools?

Before I forget, will the people using Blender 2.79's XPS Tools add-on updater receive updates for the 2.80 version too?
Just want to make sure people using Blender 2.79 aren't automatically updating to an incompatible version.

Have a great new year!

**Comment by johnzero7** [comment]
Yes, I have been testing the changes submitted by @lekarsenten and they work flawlessly. They are already pulled to master. So use the update to get the master and voila!

Unfortunately yes. When the updater addon was incorporated, I didn't put any kind of limitation. Just in v1.8.6 I limited the upper version to download. So any release previous to v1.8.6 can potentially download an incompatible version of the addon. I read the documentation of the updater, but looks like at this point there is nothing I could do to fix this situation in previous releases (not mentioning that I could delete ALL releases, limiting the updater and re-release them all). 

PS: Never mind all that. I Just found out the updater is broken too in the latest nighly build. No rest for the wicked I guess.

**Comment by johnzero7** [comment]
Now the addon creates a collection for the imported model name "XPS Model".
Updated and fixed the addon-updater.
All changes are included in Master branch and release 1.9.1
