### ISSUE TITLE
Revert progress_report location for 2.79 branch

### ISSUE THREAD

**Issue by ldo** [johnzero7/XNALaraMesh#38]
I gather the 2.79 branch is still supposed to be compatible with Blender 2.79._x_. It isn’t quite, since you seem to have included a change specific to Blender 2.8. The following patch fixes this:

    diff --git a/export_obj.py b/export_obj.py
    index c07dd35..756865f 100644
    --- a/export_obj.py
    +++ b/export_obj.py
    @@ -27,7 +27,7 @@ import mathutils
     import operator
     import bpy_extras.io_utils

    -from progress_report import ProgressReport, ProgressReportSubstep
    +from bpy_extras.wm_utils.progress_report import ProgressReport, ProgressReportSubstep

     def name_compat(name):
    diff --git a/import_obj.py b/import_obj.py
    index 0d20772..2c75a58 100644
    --- a/import_obj.py
    +++ b/import_obj.py
    @@ -41,7 +41,7 @@ import mathutils
     from bpy_extras.io_utils import unpack_list
     from bpy_extras.image_utils import load_image

    -from progress_report import ProgressReport, ProgressReportSubstep
    +from bpy_extras.wm_utils.progress_report import ProgressReport, ProgressReportSubstep

     def line_value(line_split):

Note this is only meant for your 2.79 branch.

**Comment by johnzero7** [comment]
Indeed the branch 2.79 is for blender 2.79.
I checked and the branch its still fully compatible with Release 2.79b.
The changes in the package of ProgressReport you are making reference are not in the Release version of Blender 2.79b, but are included the in the nightly builds of 2.79.

In the download page says this versions are stable and production ready. So I guess I should try to make the addon compatible with both version of 2.79. 

Thanks for the help, but this patch breaks compatibility with the release version 2.79b and all previous.

**Comment by ldo** [comment]
Ah, OK. Yes, I think it needs to be compatible both ways, because Blender’s 2.7 branch is still having new commits added to it.

**Comment by ldo** [comment]
How about this for a patch that works both ways:

    diff --git a/export_obj.py b/export_obj.py
    index c07dd35..59ca3fd 100644
    --- a/export_obj.py
    +++ b/export_obj.py
    @@ -27,8 +27,13 @@ import mathutils
     import operator
     import bpy_extras.io_utils

    -from progress_report import ProgressReport, ProgressReportSubstep
    -
    +try :
    +    from bpy_extras.wm_utils.progress_report import \
    +        ProgressReport, ProgressReportSubstep
    +except ImportError :
    +    from progress_report import \
    +        ProgressReport, ProgressReportSubstep
    +#end try

     def name_compat(name):
         if name is None:
    diff --git a/import_obj.py b/import_obj.py
    index 0d20772..5574f66 100644
    --- a/import_obj.py
    +++ b/import_obj.py
    @@ -41,8 +41,13 @@ import mathutils
     from bpy_extras.io_utils import unpack_list
     from bpy_extras.image_utils import load_image

    -from progress_report import ProgressReport, ProgressReportSubstep
    -
    +try :
    +    from bpy_extras.wm_utils.progress_report import \
    +        ProgressReport, ProgressReportSubstep
    +except ImportError :
    +    from progress_report import \
    +        ProgressReport, ProgressReportSubstep
    +#end try

     def line_value(line_split):
         """

**Comment by johnzero7** [comment]
Thanks again.
The patch is merged in the branch 2.79 and in the addon release v1.8.7
