### ISSUE TITLE
Error when importing Blender 2.79 Script 1.8.7

### ISSUE THREAD

**Issue by calypsoup** [johnzero7/XNALaraMesh#39]
![untitled](https://user-images.githubusercontent.com/28690893/51366896-1bf91b80-1af9-11e9-8770-c79034827903.jpg)

It imports few stuff but many stuff is missing 
![untitled2](https://user-images.githubusercontent.com/28690893/51366937-59f63f80-1af9-11e9-9097-7850d3ec59a6.png)

**Comment by cupcakewarp** [comment]
im having the same issue

**Comment by calypsoup** [comment]
I used 1.8.0 Version of the tool and it didn't give any error

**Comment by Marcelievsky** [comment]
Same issue here. I noticed it when the mesh has no textures assigned to it
