### ISSUE TITLE
Error While Trying to install

### ISSUE THREAD

**Issue by RiotingSpectre** [johnzero7/XNALaraMesh#40]
![image](https://user-images.githubusercontent.com/43814896/52226155-7988b880-28ac-11e9-80da-fbbf9b3ad60e.png)

How does one fix this?

**Comment by ldo** [comment]
As a general rule, I would recommend you please do not post pictures of text error messages. Copy and paste the text itself.

I’m sure I speak for the maintainer of this repo, and for all other repo maintainers.

**Comment by Gnates** [comment]
> 
> 
> As a general rule, I would recommend you please do not post pictures of text error messages. Copy and paste the text itself.
> 
> I’m sure I speak for the maintainer of this repo, and for all other repo maintainers.

@ldo 
You're right. I've made this same mistake before. 
Copy and pasting the text error itself makes it easier to log and search for this issue.
Plus, there is always a chance the image host may stop hosting the image.

**Comment by Horizon341** [comment]
Been having the same problem

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh-master\__init__.py", line 68
    auto_check_update : bpy.props.BoolProperty(
                      ^
SyntaxError: invalid syntax

**Comment by rockcabbage** [comment]
same exact error here

**Comment by lexvi** [comment]
Same issue.
ran it trough python syntax checker and its complaining about the ":" in this thing "auto_check_update : bpy.props.BoolProperty("

(tried to fix it myself but i have no idea how python works lol)

**Comment by Deruk** [comment]
I've got the same error. Any solution yet?

**Comment by DionGrendelman** [comment]
Any solutions?

**Comment by sSubtl** [comment]
Yea. if you're having the issue, on the download page go to releases just above clone or download and scroll till you find v1.1, apparently this blender version only works with this XPS version, hope this helped
![awdsad](https://user-images.githubusercontent.com/52965727/61299226-07d17500-a823-11e9-9f48-489c9edebe99.PNG)

**Comment by sSubtl** [comment]
> ![image](https://user-images.githubusercontent.com/43814896/52226155-7988b880-28ac-11e9-80da-fbbf9b3ad60e.png)
> 
> How does one fix this?

Yea. if you're having the issue, on the download page go to releases just above clone or download and scroll till you find v1.1, apparently this blender version only works with this XPS version, hope this helped
![awdsad](https://user-images.githubusercontent.com/52965727/61299226-07d17500-a823-11e9-9f48-489c9edebe99.PNG)

**Comment by johnzero7** [comment]
This error happens when you installing 1.9.X on blender 2.79
You need to use:
Blender 2.79 => XPSTools 1.8.X
Blender 2.80 => XPSTools 1.9.X

if you used the updater, it might have updated to the wrong version. Try downloading manually the version of the addon for your version of blender. This should be fixed in the latest version of the addon.
