### ISSUE TITLE
Import Failure

### ISSUE THREAD

**Issue by ldo** [johnzero7/XNALaraMesh#41]
When I try importing this model: https://www.deviantart.com/jc-starstorm/art/Starship-Cockpit-592403166 I seem to end up with no objects created.

**Comment by rilex037** [comment]
same here, importing https://www.deviantart.com/shuubaru/art/DOAX3S-Ayane-Salmon-Roe-DL-809947250, ends up with XPS Model collection with nothing in it

**Comment by johnzero7** [comment]
This issue was in the release for the BETA, the release version is fixed.
