### ISSUE TITLE
KeyError [xps_panels] with 1.9.1

### ISSUE THREAD

**Issue by Bluscream** [johnzero7/XNALaraMesh#44]
![image](https://user-images.githubusercontent.com/3318223/56624315-ab522580-6638-11e9-9c7f-a65c7103c3f5.png)

**Comment by ldo** [comment]
As a general rule, I would recommend you please do not post pictures of text error messages. Copy and paste the text itself.

I’m sure I speak for the maintainer of this repo, and for all other repo maintainers.

**Comment by Bluscream** [comment]
If I could copy tooltips, I would do it ...

**Comment by ldo** [comment]
If you run Blender from a terminal window, the error message should appear in the terminal. If you run it from a menu or icon, then they should go in the [`~/.xsessionerrors`](http://wiki.wlug.org.nz/XSessionErrors) file.

**Comment by Gnates** [comment]
> 
> 
> If I could copy tooltips, I would do it ...

Hi, if you change the **Editor Type** to either **Python Console** editor or **Info** editor, you can select the block of error messages, then **Ctrl+C** to copy.

**Comment by pixelbath** [comment]
Here is the same error from 1.9.2, latest Blender 2.8 build:

`Traceback (most recent call last):
  File "C:\Users\pixelbath\Desktop\blender-2.8\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\pixelbath\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\__init__.py", line 56, in <module>
    _modules_loaded = [_namespace[name] for name in _modules]
  File "C:\Users\pixelbath\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\__init__.py", line 56, in <listcomp>
    _modules_loaded = [_namespace[name] for name in _modules]
KeyError: 'xps_panels'`

**Comment by seangx** [comment]
same error with blender 2.80 Beta macOS 64 bit

**Comment by SpotlightKid** [comment]
I get the same error in version 1.8.7 with Blender 2.79.

As a quick hack, changing line 56 in `XNALaraMesh/__init__.py` to the following seems to have fixed the issue for me:

    _modules_loaded = [_namespace[name] for name in _modules if name in _namespace]
