### ISSUE TITLE
How to get XPS toolbar in Blender 2.80

### ISSUE THREAD

**Issue by Bluscream** [johnzero7/XNALaraMesh#45]
I can't seem to find how to get this thing in the new blender

.|.
V

![image](https://user-images.githubusercontent.com/3318223/56624995-78f5f780-663b-11e9-841f-fbc63f0505f4.png)

**Comment by Gnates** [comment]
Hi, it should be located in the 3D Viewport's Properties Shelf/Panel.
Press the **N** key to open it.
