### ISSUE TITLE
Parts of stages look transparent

### ISSUE THREAD

**Issue by narbartor** [johnzero7/XNALaraMesh#49]
I've been having this problem in 2.8 where when I import a stage, a lot of it has sort of a transparent look
![image](https://user-images.githubusercontent.com/33747159/58368259-28650900-7f1d-11e9-877d-4e3102df37b6.png)

This is how it actually looks like:
![image](https://user-images.githubusercontent.com/33747159/58368265-3c106f80-7f1d-11e9-9d2d-321cf495312b.png)

**Comment by 0Curtain0** [comment]
@narbartor Hi, not sure if this is what you are looking for, in the [Blender - Common Mistakes & Tips](https://open3dlab.com/tutorials/view/17/) page, take a look at **# 15. My 3D Model is missing faces (see-through) or has completely black texture!**
