### ISSUE TITLE
Invert Normal Node?

### ISSUE THREAD

**Issue by ArieLeo** [johnzero7/XNALaraMesh#50]
What the reason of inverting the normal map? it well literally inverting the normal vector which causing weird shading in eevee
![image](https://user-images.githubusercontent.com/6450517/60740779-89124780-9f99-11e9-9a73-ef8bb26fd4d6.png)
![image](https://user-images.githubusercontent.com/6450517/60740786-8fa0bf00-9f99-11e9-9579-176fa1cd73ef.png)

and here's the result if i bypass the invert node
![image](https://user-images.githubusercontent.com/6450517/60740808-a515e900-9f99-11e9-830a-92233b22eb19.png)

as you can see bypassing the invert normal node giving me correct normal direction.

I'm just wondering why the normal have to be inverted from the start.

**Comment by johnzero7** [comment]
Blender and XPS have different coordinate systems.
Blender is X+Y+Z+
XPS is X+Y-Z+

That means that to get the same result in XPS and Blender you need to invert the Green channel (or Y channel).
The addon created that node and assigns the values R0 G1 B0 to invert only the Green to see the same result in Blender that you would get in XPS.

It uses 0 to leave the channel as it is and 1 to invert it. Any other value will produce wired results, for example .5 will nullify the channel

**Comment by chocmake** [comment]
So this was what was inverting the lighting of the scene. Btw using the latest version of the plugin the values weren't as per the above post, but instead to R0 G3 B4, any idea why? As resetting it to the values described above fix the inverted lighting issue. @johnzero7 

Default values in latest version (checked in multiple different model imports):

![Invert node default](https://user-images.githubusercontent.com/34178938/62428577-995b4500-b746-11e9-8736-778f3310cd08.png)

GIF of inverted lighting and fix of the invert node values:

![Example](https://user-images.githubusercontent.com/34178938/62428690-92810200-b747-11e9-9a04-82f515a243d3.gif)
