### ISSUE TITLE
Blender 2.80 Feature - Import XPS Model into the Active Collection

### ISSUE THREAD

**Issue by 0Curtain0** [johnzero7/XNALaraMesh#53]
Hey, this was something I overlooked when I posted a similar feature request awhile back. 
For common 3D formats (OBJ, DAE, FBX, etc.), by default, they appear to import into the active or last selected collection in the Blender Outliner, which can be useful during large projects with multiple collections within each other.

Is it possible to add an option in the import menu to import the XPS model or XPS model collection into the active collection? 
Not sure what should be the default behavior, but I'm just throwing some ideas.

**Comment by johnzero7** [comment]
Thanks for noticing this!
Most of the importers seem to have this behavior by default, so for consistency I added it to the addon.
