### ISSUE TITLE
Rigify or Mhx converter

### ISSUE THREAD

**Issue by brehiner** [johnzero7/XNALaraMesh#57]
This addon is amazing but for animating in a smart IK rigging doesn't bring anything, so I would like to know if you are going to implement a system rigging like mhx2 or rigify. this for improving the features.

**Comment by 0Curtain0** [comment]
I don't know anything about Mhx converter, but it would be cool if XPS tools had a button that can apply IK controls to feet or hands based on the detected bone names. The challenging part would be the pole targets, but that can be adjusted manually. 

@brehiner do you have a demonstration of the Mhx converter and what it does?

**Comment by johnzero7** [comment]
I don't think XPSTools will ever add any IK rig functionality.
The XNALara model files can't store any IK information so the addon would have to guess everything.

Rigify already does that, so the XPS addon would not add anything new or better suited.

**Comment by 0Curtain0** [comment]
@brehiner @johnzero7  
A few days ago, **NecroCainALX** sent me a message with a link to an interesting rigging add-on that is being developed:  
- **Auto IK Rigger**  
- https://www.youtube.com/watch?v=NLRrwpD8zX8
