### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by machiex** [johnzero7/XNALaraMesh#59]
TypeError: bpy_struct: item.attr = val: enum "CHANNEL_PACKED" not found in ('STRAIGHT', 'PREMUL')
location: <unknown location>:-1

XNALaraMesh.2.0.0 
 blender-2.80.0-git.009dbc2bc9fb-windows64

When I import the model file
 it is just display Bone information
what wrong??

**Comment by johnzero7** [comment]
Tested in released 2.80 and 2.81 and works fine.
The hash is from an old pre-realaese of 2.80.
Try updating blender.
