### ISSUE TITLE
XPS Tools 2.0 not working with Blender 2.81/2.81a

### ISSUE THREAD

**Issue by PteJack** [johnzero7/XNALaraMesh#61]
First off JohnZero7, I would like to thank you for your dedication to the modeling community and for this most excellent tool. As a tutorial writer I use it regularly and link your GitHub for the tool. 
I posted a note on this a few days ago on your Deviantartist page as well.

Reading through the issues here I see that this situation has been reported, but as 2.81 was still in alpha, you wanted to wait, which with the changes happening in 2.8x is completely understandable.  
2.81 has been officially released and has already been fixed up to 2.81a.  I'm still receiving the same errors in 2.81a as I did in 2.81.

Here is an example of the situation in Blender 2.81 [Situation](https://i.imgur.com/haZlwpT.png) 

With 2.81a I am getting the same results on import and the errors in the Blender System console are the same...  I can provide the XPS model I'm trying to import if required, just let me know...

Thanks
Error log, Blender 2.81a (v2.81.16)
``
------------------------------------------------------------
---------------EXECUTING XPS PYTHON IMPORTER----------------
------------------------------------------------------------
Importing file:  C:\Users\Brad\Desktop\xps_lisa_park\Lisa casual\xps.xps
rootDir: C:\Users\Brad\Desktop\xps_lisa_park\Lisa casual
File: C:\Users\Brad\Desktop\xps_lisa_park\Lisa casual\xps.xps
Reading Header
Header Found
Tangent Space Normal Map Swizzel Coordinates:
X+ Y- Z+

Reading Bones
Read 1249 Bones
Reading Meshes
Read 11 Meshes
Importing Armature 1249 bones

---*** Importing Mesh 22_belt2_0.1_16_16 ***---
UV Layer Count: 1
Texture Count: 7
Created Mesh: 22_belt2_0.1_16_16
New Mesh = 22_belt2_0.1_16_16
Loading Texture: belt_diffuse.png
Loading Texture: belt_lightmap.png
Loading Texture: belt_bump.png
Loading Texture: lightmap_white.png
Loading Texture: bumpmap_flat.png
Traceback (most recent call last):
  File "C:\Users\Brad\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\XNALaraMesh-master\xps_tools.py", line 164, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\Brad\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 78, in getInputFilename
    status = xpsImport()
  File "C:\Users\Brad\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 159, in xpsImport
    meshes_obs = importMeshesList(armature_ob)
  File "C:\Users\Brad\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 478, in importMeshesList
    for meshInfo in newMeshes]
  File "C:\Users\Brad\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 478, in <listcomp>
    for meshInfo in newMeshes]
  File "C:\Users\Brad\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 615, in importMesh
    material_creator.makeMaterial(xpsSettings, rootDir, mesh_da, meshInfo, flags)
  File "C:\Users\Brad\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\XNALaraMesh-master\material_creator.py", line 170, in makeMaterial
    makeNodesMaterial(xpsSettings, materialData, rootDir, mesh_da, meshInfo, flags)
  File "C:\Users\Brad\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\XNALaraMesh-master\material_creator.py", line 338, in makeNodesMaterial
    mappingCoordNode.scale = (texRepeater, texRepeater, texRepeater)
AttributeError: 'ShaderNodeMapping' object has no attribute 'scale'

location: <unknown location>:-1

location: <unknown location>:-1
Info: Deleted 1 object(s)

**Comment by 0Curtain0** [comment]
Hey PteJack, I used to watch your tutorials when I used to use SFM; thank you for those resources. 
I switched to Blender full-time and mostly focused on organizing educational resources for new Blender users: 
- [Blender - Common Mistakes & Tips](https://www.deviantart.com/xcurtainx/journal/Blender-Common-Mistakes-and-Tips-756854058)
- [Blender Guide - Rigging & Weight Painting](https://www.deviantart.com/xcurtainx/journal/Blender-Guide-Rigging-Weight-Painting-785437846) 
------
Regarding your error in Blender 2.81a with XPS Tools v2.0.0, I wasn't able to reproduce it with my setup.

Operating System: **Pop!_OS 19.04** (based on Ubuntu)
Blender **v2.81a** Official Release (non-Steam version for Linux tar.bz2)
XPS Tools **v2.0.0** 

I tested with the following XPS model: [King of Fighters: All Star' Shiranui Mai](https://www.deviantart.com/lezisell/art/King-of-Fighters-All-Star-Shiranui-Mai-XPS-ONLY-822538025) 

Do you have a link to download the XPS model you used? 

Any luck with factory resetting Blender 2.81a and reinstalling XPS Tools v2.0.0?

**Comment by PteJack** [comment]
Sorry for the tardy, Christmas and all... LOL  

Ok, the model I'm trying to import is this one by Tokami-Fuko. It looks like they have pulled the download, but I was handed the model by someone who is trying to port it into SFM.  I was going to use it as an example for one of my tutorials for 2.81a but when I tried to import it, I got the result I posted.

I have placed the model in my dropbox and you can grab it here.. https://www.deviantart.com/tokami-fuko/art/XPS-Lisa-Park-possible-download-498623197

Now, here's something even stranger and it might point to the something to do with how the model was created.

Lisa model in 2.79b (no problem)
https://i.imgur.com/2WqQnDe.png

Lisa Model in 2.80 (no problem)
https://i.imgur.com/NkSjRJI.png

Now I went out and grabbed the model pack you tried and imported the mai(94) model into 2.81a. Then imported the Lisa model into the same session as well... Here's the result...
https://i.imgur.com/Om7LE8K.png

As the author has pulled the download, I'm starting to suspect it may be something to do with the model itself. But why would it import properly into the other 2 versions but not 2.81a?

**Comment by 0Curtain0** [comment]
I just tried importing that Lisa Park model into Blender 2.81a, and I got the same problem you got, as shown in that picture. 
I have no idea why that's happening. 

By chance, did you get an error while extracting the xps_lisa_park_by_tokami_fuko_d88vczo.rar file?

Also, did you come across any other XPS models that fail to import in this way?

**Comment by PteJack** [comment]
Yes, I did, I got a checksum error from the hair_s.png, but I don't think a specular texture would cause this issue, especially if it imports correctly in the earlier versions.

No, this was the first model I've actually attempted to import to 2.81a and as you see the mai model came in without a problem.  What I might try is exporting Lisa as an XPS from 2.79b and see if I can import her in 2.81a. After seeing Mai come in without a problem, I might have cried Wolf too soon and it's just the model. 

But it still doesn't answer why she imports into the earlier versions but not in 2.81a.  It's looks like something fell out of line between the add-on and the core somewhere. Maybe a UTF8 character in the model that didn't convert properly.

**Comment by johnzero7** [comment]
Another API change in Blender 2.81, precisely in the ShaderNodeMapping node. https://wiki.blender.org/wiki/Reference/Release_Notes/2.81/Python_API
#In 2.80 was:
`mappingCoordNode.scale = (texRepeater, texRepeater, texRepeater)`
#in 2.81 is:
`mappingCoordNode.inputs['Scale'].default_value = (texRepeater, texRepeater, texRepeater)`

This only affected XPS render groups that supported scaling of the textures, like group 22.
This is why only some models could not be imported in Blender 2.81.
You can update to master using the addon-updater in the preferences or wait for a new release.

Thanks for you patience and keep enjoy this addon!
