### ISSUE TITLE
2.79 version cannot be added to 2.79 blender

### ISSUE THREAD

**Issue by CraftyMaelyss** [johnzero7/XNALaraMesh#62]
I downloaded the branch pack for 2.79 blender, however when I go into user preferences and try to install the addon, it doesn't show a confirmation or error message, it just simply doesn't add it. I've tried adding on from both the zip file and the unzipped folder, both with no results.

**Comment by 0Curtain0** [comment]
@CraftyMaelyss Hi, I'm not a developer, but I am curious to know the exact url address of the link you used to download the add-on. 
Right click the link that you downloaded from, then copy and paste the link here in the comments.

**Comment by CraftyMaelyss** [comment]
@0Curtain0 This is the link I used:
https://github.com/johnzero7/XNALaraMesh/tree/blender-2.79

**Comment by 0Curtain0** [comment]
@CraftyMaelyss did you try downloading it from the release section?  
- https://github.com/johnzero7/XNALaraMesh/releases  

I believe **v1.8.7** is the latest version for **Blender 2.79**
