### ISSUE TITLE
latest version of XPS file cannot be imported

### ISSUE THREAD

**Issue by Kendaman** [johnzero7/XNALaraMesh#65]
hi, XPS was recently updated.

The current xps.xps file has changed format or cannot be imported with the blender plugin.
.ascii type is old format and can be imported.

**Comment by johnzero7** [comment]
Thanks for letting me know there was a new XPS version.
Release [2.0.2](https://github.com/johnzero7/XNALaraMesh/releases/tag/v2.0.2) of the addon adds suppor for the new file format
