### ISSUE TITLE
re:materials convertor

### ISSUE THREAD

**Issue by meta-androcto** [johnzero7/XNALaraMesh#7]
hi, 
I'm Brendon, I help out with Blender addons & would like to ask you about your materials converter.

I've been testing out your materials converter & import & really like it. your conversion works quite well on many other formats also. I would be interested in replacing the current materials converter in Blender addons_contrib with something very similar to yours. Would you be interested in developing this area more? Are you able to separate the materials conversion out into it's own folder?
My concept script is here: https://github.com/meta-androcto/blenderpython/tree/master/scripts/addons_extern/AF_materials_specials
In this I'm updating the materials utils addon in blender & have made an initial switch & added a few things. I would like to submit this to Blender soonish & would prefer not to leave out the conversion. (current addons_contrib version would not make it.)
Thanks. Let me know what you think & keep up the good work. Your importer works better than most in blender also. :)

**Comment by johnzero7** [comment]
Hi Brendon,
wow, that's quite a collection of addons.

Looks like my converter is based in an older version of that very same script. I only aimed to convert XNALara materials (which are very simple) to Cycles, so there is a lot to improve if you want to use this script for materials in general. There are things like the specularity nodes that don't look rigth to me, and the node positing is specially shameful.
Yeah, I would like to improve it.
Everything up to the creation of the operators is contained in the file **material_converter.py**. So you can separate it and modify it as you need. 

It's nice to see you liked the importer and material converter. Thank you.
