### ISSUE TITLE
node type shaderNodeBsdfPrincipled undefined while import xps model to blender 2.78

### ISSUE THREAD

**Issue by roy-sanada** [johnzero7/XNALaraMesh#70]
I am using blender 2.78 and XPS tools 1.8.7. While I tried to import the RenderGroupTester which download from dropbox with this tool. Part of the model lost. Only one set cube and spherical and all bones are shown. But I can  see total 45 set cube and spherical in XNALara XPS. And it show the log as I attach "node type shaderNodeBsdfPrincipled undefined". I am not sure whether it due to incorrect setting or bug?
![blendererror1](https://user-images.githubusercontent.com/25880854/84596977-5e13c180-ae93-11ea-85bc-d31f7a58c025.png)
![xps](https://user-images.githubusercontent.com/25880854/84596987-666bfc80-ae93-11ea-88c6-613240aeb335.png)

**Comment by roy-sanada** [comment]
I found I can import XPS successfully after replace XPS tools 1.8.7 with 1.8.4

**Comment by johnzero7** [comment]
1.8.7 uses the Principled Shader which was introduced in Blender 2.79 so is not compatible with previous versions of Blender. Recommend update Blender

**Comment by roy-sanada** [comment]
> 1.8.7 uses the Principled Shader which was introduced in Blender 2.79 so is not compatible with previous versions of Blender. Recommend update Blender

Many many thanks for your reply. I can use 1.8.7 tools now.
